mod box_assigns;
mod closure_convert;
mod coercions;
mod collect_assigns;
mod compile;
pub mod constructors;
pub mod from_js;
mod fv;
mod insert_returns;
mod methods;
mod operators;
mod operators_z3;
mod pretty;
mod select_method_call;
pub mod syntax;
mod type_checking;
mod typeinf;
mod typeinf_env;
mod walk;

pub use compile::compile;
